#!/bin/bash

# Script to remove generated files from Git tracking while keeping them locally
# These files are now excluded via .gitignore and can be regenerated

echo "🧹 Removing generated model artifacts from Git tracking..."
echo ""

# Array of files to remove
files_to_remove=(
    "models/feature_importance.json"
    "models/feature_names.json"
    "models/full_metrics.json"
    "models/model_comparison.json"
    "models/model_comparison.md"
    "models/model_metadata.json"
    "models/preprocessor_config.json"
    "models/production_model_metadata.json"
    "models/xgboost_feature_importance.json"
    "models/xgboost_full_metrics.json"
    "models/xgboost_metadata.json"
    "models/comparison_report.html"
)

# Counter for successfully removed files
removed_count=0
not_found_count=0

# Remove each file from Git tracking
for file in "${files_to_remove[@]}"; do
    if git ls-files --error-unmatch "$file" >/dev/null 2>&1; then
        echo "  ✓ Removing: $file"
        git rm --cached "$file" >/dev/null 2>&1
        ((removed_count++))
    else
        echo "  ⊘ Not tracked: $file"
        ((not_found_count++))
    fi
done

echo ""
echo "📊 Summary:"
echo "  • Files removed from tracking: $removed_count"
echo "  • Files not tracked: $not_found_count"
echo ""

if [ $removed_count -gt 0 ]; then
    echo "✅ Files have been removed from Git tracking but remain in your local filesystem."
    echo ""
    echo "Next steps:"
    echo "  1. Review the changes: git status"
    echo "  2. Commit the changes: git commit -m 'chore: remove generated artifacts from version control'"
    echo "  3. Push to remote: git push"
else
    echo "ℹ️  No tracked files needed to be removed."
fi

echo ""
echo "Note: These files can be regenerated by running the model training scripts."
